config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }
  
  devise_for :admins,controllers:{
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update, :destroy]
    resources :genres,only: [:index, :create, :edit, :update, :destroy]
    resources :scenes,only: [:index, :create, :edit, :update, :destroy]
  end
  
  scope module: :public do
    root to: 'homes#top'
    resources :users, only: [:show, :edit ,:update] do
      member do
        get :favorites
        get :follows
        get :followers
      end
      collection do
        get :unsubscribe
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
    end
    
    resources :notifications, only:[:index] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :chats, only:[:show, :create, :destroy]
    
  end
 
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true,length:{ maximum:15 }
  
end

app/controllers/admin/scenes_controller.rb
class Admin::ScenesController < ApplicationController
before_action :authenticate_admin!  
  
def index
  @scenes = Scene.page(params[:page]).per(10)
  @scene = Scene.new
end

def create
  @scene = Scene.new(scene_params)
  if @scene.save
    redirect_to admin_scenes_path
  else
    @scenes = Scene.page(params[:page]).per(10)
    render 'index'
  end
end

def edit
  @scene = Scene.find(params[:id])
end

def update
  @scene = Scene.find(params[:id])
  if @scene.update(scene_params)
    redirect_to admin_scenes_path
  else
    render 'edit'
  end
end

def destroy
  @scene = Scene.find(params[:id])
  if @scene.destroy
    redirect_to admin_scenes_path
  else
    render 'index'
  end
end

private

def scene_params
  params.require(:scene).permit(:name)
end

  
end

app/views/admin/scenes/edit.html.erb
<div class ="container mb-5">
  <div class ="row">
    <h1 class ="col-12 text-center mt-5">Edit Scene</h1>
    <% if @scene.errors.any? %>
    <div class ="col-12 text-center">
      <%= @scene.errors.count %> errors have occurred<br>
      <% @scene.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>
    <% end %>
    <div class ="col-12 text-center mt-2">
    <%= form_with model:@scene,url: admin_scene_path(@scene),method: :patch,local:true do |f| %>
    <%= f.text_field :name, autofocus: true %><br>
    <%= f.submit "update",class:"text-center mt-2" %>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/scenes/index.html.erb
<div class ="container mb-5">
  <div class ="row">
    <h1 class ="col-12 text-center mt-5">Scene List</h1>
     <% if @scene.errors.any? %>
    <div class ="col-12 text-center">
      <%= @scene.errors.count %> errors have occurred<br>
      <% @scene.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>
    <% end %>
    <div class ="col-12 text-center mt-2">
    <%= form_with model:@scene,url: admin_scenes_path(@scene),method: :post,local:true do |f| %>
      <%= f.text_field :name, autofocus: true %>
      <%= f.submit "send" %>
    <% end %>
    <table class ="admin_table col-12 text-center mt-5">
      <thead>
        <th class ="admin_th">scene name</th>
        <th class ="admin_th"></th>
        <th class ="admin_th"></th>
      </thead>
      <tbody>
      <% @scenes.each do |scene| %>
        <tr>
         <td class ="admin_td"><%= scene.name %>
         <td class ="admin_td"><%= link_to "Edit",edit_admin_scene_path(scene),class:"btn btn-sm btn-success" %></td>
         <td class ="admin_td"><%= link_to "Destroy",admin_scene_path(scene),method: :delete,data: { confirm: 'Do you really want to delete this?' },class: 'btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>  
    <%= paginate @scenes %>
    </div>
  </div>
</div>