config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }
  
  devise_for :admins,controllers:{
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update, :destroy]
    resources :genres,only: [:index, :create, :edit, :update, :destroy]
    resources :scenes,only: [:index, :create, :edit, :update, :destroy]
  end
  
  scope module: :public do
    root to: 'homes#top'
    resources :users, only: [:show, :edit ,:update] do
      member do
        get :favorites
        get :follows
        get :followers
      end
      collection do
        get :unsubscribe
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
    end
    
    resources :notifications, only:[:index] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :chats, only:[:show, :create, :destroy]
    
  end
 
end

app/views/layouts/_footer.html.erb
<footer class="text-white text-center">
  <p class="copyright mt-2">
    COPYRIGHT©2021 TravelMania.Co.,LTD.All rights Reserved.<br>
    <p class ="contact">contact:&nbsp;&nbsp;daoqianguobu@gmail.com</p>
  </p>
</footer>
 

app/views/layouts/_header.html.erb
<header>
<div class="hamburger-menu">
  <input type="checkbox" id="menu-btn-check">
  <label for="menu-btn-check" class="menu-btn"><span></span></label>
  <div class="menu-content">
    <ul>
    <li>
      <h4><%= link_to "TravelMania",root_path,class: 'site_logo' %></h4>
    </li>
  <% if user_signed_in? %>
    <li>
      <%= link_to new_post_path do %>
        <i class="fas fa-camera-retro fa-2x"></i>
      <% end %>
    </li>
    
    <li>
      <%= link_to favorites_user_path(id: current_user) do %>
        <i class="far fa-heart fa-2x"></i>
      <% end %>
    </li>
    <li>
      <%= link_to user_path(id: current_user) do %>
      <i class="far fa-user fa-2x"></i>
      <% end %>
    </li>
   
    <% if current_user.passive_notifications.where(checked: false).any? %>
      <i class="fa fa-circle" style="color: gold;"></i>
    <% end %>
    <li>
      <%= link_to notifications_path do %>
      <i class="far fa-bell fa-2x"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    </li>
  <% elsif admin_signed_in? %>
    <li>
      <%= link_to "logout", destroy_admin_session_path, method: :delete %>
    </li>
    <li>
      <%= link_to "area", admin_areas_path %>
    </li>
    <li>
      <%= link_to "genre", admin_genres_path %>
    </li>
    <li>
      <%= link_to "scene", admin_scenes_path %>
    </li>
    <li>
      <%= link_to "user", admin_users_path %>
    </li>
  <% else %>
    <li>
      <%= link_to "signup",  new_user_registration_path %>
    </li>
    <li>
      <%= link_to "login", new_user_session_path %>
    </li>
  <% end %>

    </ul>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelmania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Corben:700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render "layouts/header" %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>